### ISSUE TITLE
cant find module index.

### ISSUE THREAD

**Issue by guruward** [ammmir/node-oauth2-provider#29]
/usr/local/bin/node node-oauth2-provider/examples/simple_express3.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'index'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Volumes/Fileservers/Mobinnov-1/Projects/medOAuth/node-oauth2-provider/examples/simple_express3.js:3:22)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)

Process finished with exit code 1

**Comment by ammmir** [comment]
how are you invoking the example?

**Comment by guruward** [comment]
Exactly as the read me.md

Sent from my iPhone

On Feb 21, 2013, at 4:18 PM, "Amir Malik" <notifications@github.com<mailto:notifications@github.com>> wrote:

how are you invoking the example?

**Comment by guruward** [comment]
I ran npm install

the error is the index.js  I'm assuming its not compiling.

On Feb 21, 2013, at 4:18 PM, Amir Malik <notifications@github.com<mailto:notifications@github.com>>
 wrote:

how are you invoking the example?

**Comment by ammmir** [comment]
ah, that's assuming you downloaded the code from the repo. just copy out the example and change `../index` in the require to `oauth2-provider` and you'll be set.

**Comment by guruward** [comment]
Thank you

Sent from my iPhone

On Feb 21, 2013, at 11:44 PM, "Amir Malik" <notifications@github.com<mailto:notifications@github.com>> wrote:

ah, that's assuming you downloaded the code from the repo. just copy out the example and change ../index in the require to oauth2-provider and you'll be set.
